baseurl = "/"
languageCode = "fr-fr"
title = "un peu d'R"
theme = "hugo-lithium"
googleAnalytics = "UA-169346462-1"
disqusShortname = "petzi"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/lewishounkpevi"
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/Afafa_h"
[[menu.main]]
    name = "Linkedin"
    url = "https://www.linkedin.com/in/lewishounkpevi/"
[[menu.main]]
    name = "Contact"
    url = "/contact.html"

[params]
    description = "A website built through Hugo and blogdown."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "0.jpg"

    [params.logo]
    url = "0.jpg"
    width = 50
    height = 50
    alt = "Logo"

